import "./globals.css";
import Navbar from "@/components/Navbar";
import TransitionProvider from "@/components/TransitionProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className={`w-screen h-screen`}>
        <body className={`h-full`}>
        <TransitionProvider>{children}</TransitionProvider>
        </body>
        </html>
    );
}
